name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Jinaga
      run: dotnet build Jinaga --no-restore
    - name: Build Jinaga.Test
      run: dotnet build Jinaga.Test --no-restore
    - name: Test
      run: dotnet test Jinaga.Test --no-build --verbosity normal
